#!/bin/bash

for i in /sys/class/hwmon/* ; do
    NAME=$(cat "$i/name")
    if [ $NAME == $BLOCK_INSTANCE ]; then
        if [ ! -f "$i/temp1_input" ]; then
            exit
        fi
        TEMP=$(cat "$i/temp1_input")

        if [ ! -f "$i/temp1_crit" ]; then
            CRIT="80000" #80°C default
        else
            CRIT=$(cat "$i/temp1_crit")

            if [[ "$CRIT" == "0" ]]; then
                CRIT="80000"
            fi
        fi
    fi
done

if [ -z "$TEMP" ]; then
    exit
fi

OUT="$(bc <<< "scale=1; $TEMP/1000")°C"
echo $OUT

if [ "$TEMP" -gt "$CRIT" ]; then
    echo "#FF0000"
    echo "#FF0000"
fi
