#!/usr/bin/env bash

ip link show wg0vpn | grep -q UP && printf '\uf3ed\n\n#00ff00' && exit
ip link show wg1mv | grep -q UP && printf '\uf3ed\n\n#00ff00' && exit
ip link show wg2mv | grep -q UP && printf '\uf3ed\n\n#00ff00' && exit
